fix: rebuild script now uses pushd & popd so it can be ran anywhere

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -1,6 +1,10 @@
 #!/usr/bin/env bash
-nix fmt
+pushd ~/nixos || exit
+
+nix fmt &>/dev/null
 git diff -U0 '*.nix'
 echo "rebuilding nixos..."
 sudo nixos-rebuild switch --flake "$HOME/nixos#zero" | tee rebuild.log || ( grep rebuild.log --color error && exit 1)
 notify-send -e "nixos rebuilt OK!"
+
+popd || echo "failed to popd"
